project:
  type: book

book:
  title: "An Introduction to Climate Risk Analysis"
  editor: "Vivek Srikrishnan and Klaus Keller"
  date: "2/3/2023"
  edition: "3rd"
  date-format: "YYYY"
  cover-image: images/cover_with_alexander.png
  page-navigation: true
  repo-url: https://github.com/vsrikrish/CRA-book
  repo-actions: [edit, issue]
  reader-mode: true

  chapters:
    - part: "About This Book"
      chapters:
        - index.qmd
        - acknowledgements.qmd
    - part: contents/uq/intro.qmd
      chapters:
        - contents/uq/mcmc.qmd
    - part: contents/extremes/intro.qmd
        - contents/uq/extreme_models.qmd
    - references.qmd

  sidebar:
    style: "docked"
    collapse-level: 1


bibliography: bibliography/references.bib

format:
  html:
    theme: 
      light: [flatly, stylesheets/theme.scss]
      dark: [flatly, stylesheets/theme-dark.scss]
    citations-hover: true
    footnotes-hover: true
    default-image-extension: svg
    reference-location: margin
    cap-location: bottom
    title-block-banner: true
    code-overflow: wrap
    code-copy: true
    html-math-method: 
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"


crossref:
  chapters: true
number-sections: true
number-depth: 2
execute:
  eval: true
  freeze: false
citation-location: document
highlight-style: github
csl: bibliography/american-geophysical-union.csl
