project:
  type: book
  output-dir: docs

book:
  title: "An Introduction to Climate Risk Analysis"
  editor: "Vivek Srikrishnan and Klaus Keller"
  date: "2/3/2023"
  edition: "3rd"
  date-format: "YYYY"
  cover-image: images/cover_with_alexander.png
  page-navigation: true
  repo-url: https://github.com/vsrikrish/CRA-book
  repo-actions: [edit, issue]
  reader-mode: true
  output-file: "raes"
  downloads: [pdf, epub]

  chapters:
    - part: "About This Book"
      chapters:
        - index.qmd
        - acknowledgements.qmd
    - part: contents/flood/intro.qmd
      chapters:
        - contents/flood/modeling_slr.qmd
        - contents/flood/slr_model.ipynb
        - contents/flood/slr_likelihood.ipynb
    - references.qmd

  sidebar:
    style: "docked"
    collapse-level: 1

bibliography: bibliography/references.bib

format:
  html:
    theme: 
      light: [flatly, stylesheets/theme.scss]
      dark: [flatly, stylesheets/theme-dark.scss]
    citations-hover: true
    footnotes-hover: false
    default-image-extension: svg
    reference-location: margin
    cap-location: margin
    title-block-banner: true
    code-overflow: wrap
    code-copy: true
  pdf:
    documentclass: report
    links-as-notes: true
    mainfont: IBMPlexSans
    mainfontoptions:
      - Path=fonts/
      - Extension=.ttf
      - UprightFont=*-Regular
      - ItalicFont=*-Italic
      - BoldFont=*-Bold
    monofont: IBMPlexMono
    monofontoptions:
      - Path=fonts/
      - Extension=.ttf
      - UprightFont=*-Regular
      - ItalicFont=*-Italic
      - BoldFont=*-Bold
    default-image-extension: pdf
    cap-location: margin
    reference-links: true
    geometry:
      - left=1in
      - right=2in
      - top=1in
      - bottom=1.5in
      - marginparsep=0.1in
    listings: true
    include-in-header:
      - text: \usepackage{float}
  epub: 
    creator: "Vivek Srikrishnan"
    epub-fonts: 
      - fonts/IBMPlexSans-*.ttf
      - fonts/IBMPlexMono-*.ttf
    reference-location: margin
    cap-location: margin


crossref:
  chapters: true
number-sections: true
number-depth: 2
execute:
  freeze: auto
  eval: true
citation-location: document
highlight-style: github
csl: bibliography/american-geophysical-union.csl
