[projects]

    [projects.default]
    contents = [
        "1_about",
        "2_intro",
        "3_julia_basics",
        "4_plotting_time_series",
        "references"
    ]
    port=8000

    output_filename="raes_2p0"
