# Introduction
 
This chapter was written by Patrick J. Applegate and Klaus Keller. It briefly discusses climate change, uncertainty, and risk.

## Climate Risks

We begin with a very brief discussion of some key findings of climate science and the problems posed by climate change.  There are many useful reviews of these subjects, in both textbook and popular formats [@Kump2009-no; @Alley2011-by].  For high-level discussions of these topics, see the [Intergovernmental Panel on Climate Change](http://www.ipcc.ch/index.htm)'s recent reports, particularly the Technical Summaries of the IPCC's Working Groups I and II [@Stocker2013-am; @Field2013-pl].  We particularly recommend that you read chapters 1, 3, 6, 15, and 16 in @Kump2009-no before working on the exercises in this e-textbook.

Most scientists who study the climate system agree that human activities are causing surface air temperatures to increase [@Oreskes2007-fj].  Combustion of fossil fuels and changes in land use lead to increases in the concentrations of carbon dioxide, methane, and nitrous oxide in the atmosphere.  The increased concentrations of these gases trap heat near the earth's surface that would normally escape to outer space.  Temperatures have risen measurably over the last century and will probably continue to increase in the future [@Ipcc2013-px; @Collins2013-yi].

This increase in surface air temperatures affects other parts of the Earth system, notably sea level.  Rising surface air temperatures cause the water near the ocean's surface to expand, and also lead to increased rates of melting from land ice.  Global mean sea level has risen by a few tens of centimeters over the past 1-2 centuries, and could go up by more than one meter by 2100 [@Parris2012-qw; @Ipcc2013-px; @Church2013-el].

Increases in sea level create risks for people living near present-day sea level.  Sea level at a particular point along the world's coastline rises and falls over time scales of hours to days, in response to tides and storms.  Stacked on top of the long-term rise in sea level, these short-period oscillations flood normally-dry land with increased frequency [e.g. @Spanger-Siegfried2014-mx].

Fossil fuel consumption also creates benefits for people, although these benefits are unevenly distributed.  Countries with low per capita [gross domestic products](https://en.wikipedia.org/wiki/Gross_domestic_product) also tend to emit very little carbon dioxide per person.  Among countries with high per capita gross domestic products, some emit large amounts of carbon dioxide per person each year, whereas others emit comparatively little.  However, achieving good economic outcomes in today's energy economy seems to require at least some fossil fuel consumption.  Moreover, the benefits of fossil fuel consumption occur now, whereas the negative effects of climate change will take place primarily in the future.

Thus, reducing greenhouse gas emissions creates costs in terms of lost economic productivity.  Modern societies require large amounts of energy to manufacture goods, produce food, and move people from place to place.  Today, [most of that energy comes from fossil fuels](https://www.iea.org/fuels-and-technologies).  Reducing fossil fuel consumption likely means cuts to manufacturing, agriculture, or transportation, at least in the short term.

## Some Questions

The discussion in Chapter \@ref(climate-risks) leads to several interrelated questions:

1. How much carbon dioxide, and other greenhouse gases, will human societies emit in the future [e.g. @Sanford2014-rr]?
2. How much will surface air temperatures rise in response to past and future greenhouse gas emissions?
3. How much will sea level rise as a consequence of surface air temperature increases?
4. What effects will increases in temperature and sea level, as well as changes in precipitation and other climatic variables, have on people?
5. Given the benefits associated with fossil fuel consumption and the risks presented by climate change, what is the appropriate balance between economic growth, cutting greenhouse gas emissions, and building protective measures to moderate the negative effects of climate change?
6. In choosing a strategy for addressing climate change, how do we take account of values like fairness?  For example, how do we ensure that the negative impacts of climate change do not fall disproportionately on people who have not contributed to the problem?

Answering these questions requires contributions from several disciplines, including the social sciences (especially economics; questions 1, 4, and 5), meteorology (2), oceanography (3), glaciology (3), and philosophy (6).  It also requires estimating future changes, often with computer models.

Statistics also plays an important role in answering these questions, because our answers always contain some level of uncertainty.  Future changes in temperature and sea level depend on emissions (question 1), which are difficult to predict.  Moreover, climate projections are made with imperfect computer models that depend on input parameters whose values we aren't sure of.  When we make an estimate of future changes using a computer model, how sure should we be about the answer?  How can we report our answers in a way that accurately reflects the state of our knowledge?  Statistics is the discipline that provides answers to these questions.

## Types of (Un)certainty

Suppose that we wish to characterize the state of our knowledge about a future event whose outcomes can take values on the real number line.  Depending on the event in question, this quantity can be *certain*, *uncertain*, or *deeply uncertain*.  These "levels of uncertainty" [@rieschLevelsUncertainty2013] have different mathematical representations:

* If the outcome is certain, it can take just one value.
* If the outcome is uncertain, but not deeply uncertain, there is a well-defined and generally agreed-upon [probability density function](https://en.wikipedia.org/wiki/Probability_density_function) that relates different potential outcomes to the probability that they will occur (see Exercise 3 for a discussion of probability density functions).  For example, rolling a die has six possible outcomes (the integers 1, 2,... 6), and each of these outcomes is equally likely to occur if the die is fair.
* If the outcome is deeply uncertain, there is no single, agreed-upon probability density function describing the chance of observing different outcomes.

Many important questions in climate science involve deep uncertainty.  Published estimates of the climate sensitivity provide perhaps the clearest demonstration of this point.  Climate sensitivity is the change in global mean temperature that would result if carbon dioxide concentrations in the atmosphere were to double.  Many studies have estimated this quantity.  Though these studies have obtained overlapping answers, their probability density functions differ [@Collins2013-yi, their Fig. 1 in Box 12.2; @Meehl2007-zp, their Fig. 9.20].

## What is Risk?

Answering many important questions requires careful consideration of *risk*.  Risk is the harm associated with a particular bad outcome, multiplied by the chance of that bad outcome occurring.  For example, answering questions 5 and 6, above, requires considering the harms associated with future climate change, given that we are not sure how severe it will be (questions 1-4).  A possible future event can represent an important risk if it is relatively benign, but very likely to occur, or if it is very unlikely, but extremely damaging if it does happen.

Classic risk analysis typically assumes that the probability density functions relating outcomes to the chances of their occuring are well-known.  However, as noted above, many questions in climate science have deeply uncertain answers.  In these cases, other methods have to be used to assess the merits of different approaches for managing climate risk.  One such approach is robust decision making, or RDM [@Sriver2017-cc; @Hadka2015-mx], which focuses on identifying the weaknesses of particular systems and then identifying solutions which produce good results over a wide range of potential outcomes.

Risk analysis in the Earth sciences often involves considering low-probability, high-impact events.  For example, at least one study suggests that large temperature increases could make important parts of the Earth's surface metabolically uninhabitable [@sherwoodAdaptabilityLimitClimate2010].  Animals, including humans, have to maintain a body temperature within a relatively restricted range in order to survive.  Climate modeling indicates that future climate change could raise temperatures near the equator so much that human beings could not live there, except in air-conditioned buildings.  This possibility is unlikely, but would have important effects on human societies.

## "Uncertainty" vs. "Risk"

The meanings that we assign to "uncertainty", "deep uncertainty", and "risk" seem intuitive to us; however, other researchers use these words to mean quite different things.  The taxonomy we use here separates future events into groups depending on whether or not we have a good sense of the probabilities associated with different outcomes, and it distinguishes the chances of different outcomes from their consequences.  However, an influential early taxonomy of uncertainty [@Knight1921-wq] used "risk" and "uncertainty" to represent the concepts that we term "uncertainty" and "deep uncertainty," respectively.  We have also heard influential scientists use the word "uncertainty" to mean the same thing as what we term "risk."  Readers of this e-textbook should be aware of these varying definitions when looking at other sources.