---
author: "Vivek Srikrishnan and Klaus Keller"
---

# Introduction to Coastal Flood Risk

Many people live near present-day sea level [@Nicholls2008-af;@nichollsGlobalAnalysisSubsidence2021], and rises in sea level expose these people to the possibility of flooding.  For example, the ongoing increase in sea level will likely cause communities on the United States' eastern coast to experience frequent flooding within the next few decades [@Spanger-Siegfried2014-mx].

Sea level rise is caused by temperature increases, which in turn are driven by increases in carbon dioxide concentrations in the atmosphere.  Carbon dioxide is produced by human activities and natural processes.  Increases in carbon dioxide concentrations in the atmosphere enhance the trapping of infrared radiation near the Earth's surface and contribute to rises in surface air temperatures.  As the ocean absorbs some excess heat from the atmosphere, its temperature increases, causing it to expand and causing sea level rise.  Temperature increases cause melt of glaciers and ice sheets, which leads to sea level rise by adding mass to the oceans.

![Atmospheric carbon dioxide concentrations (top panel), surface air temperature change (middle panel), and sea level change (bottom panel), between 1900 and ~2015.  All three quantities rise over this period, possibly suggesting a causal relationship between them given a plausible theoretical connection. See text for discussion.](images/co2-slr.png){#fig-co2-slr}

Data covering the last century support this relationship between atmospheric carbon dioxide concentrations, temperature, and sea level (@fig-co2-slr).  The curves in the three panels of @fig-co2-slr rise together, suggesting that these variables are related. 

::: {.callout-important}
Although correlation does not prove causation, the combination of a clear relationship between variables with a plausible explanation for why they should be related is *evidence* for causation.
:::

Because carbon dioxide mixes readily in the atmosphere, measurements of atmospheric carbon dioxide concentrations at most places on the Earth's surface are relatively representative of the globe as a whole.  In contrast, both surface air temperatures and sea levels are measured at widely dispersed stations and must be aggregated to give a global mean value.  Global mean temperatures must be estimated from individual weather stations with long records [@hansenGlobalSurfaceTemperature2010]; past sea levels are estimated using data from tide gauges [@jevrejevaTrendsAccelerationGlobal2014a].  As one might expect, there are various methods for performing this aggregation, and the different methods give somewhat different answers.  However, it seems clear that both global mean surface air temperature and global mean sea level are rising.

At the same time, precipitation rates and tropical cyclone intensities are likely to increase as the climate warms [@walshTropicalCyclonesClimate2016]. This suggests that the occurrence frequencies of extreme storm surges could also change. The combination of increasing sea levels and changing storm surge frequencies would change the distribution of extreme water levels, and therefore impact the efficacy of flood risk management strategies. In this section, we will explore some tools for quantifying and assessing the future impacts of climate change on coastal flood risk.
