name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up Julia 1.7
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.7'
    - name: Install jupyter book
      run: |
        pip install jupyter-book>=0.7.0b
    - name: Install IJulia
      run: |
        julia -e 'import Pkg; Pkg.add("IJulia"); using IJulia; IJulia.installkernel("julia")'
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build contents
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html